# Generated by Django 6.0 on 2025-12-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['company__name', 'bus_number'], 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
    ]
