# Generated by Django 6.0 on 2025-12-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('driver', 'Driver seat'), ('passenger', 'Passenger seat')], default='passenger', max_length=10),
        ),
    ]
